# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/cli/master/cli/compose/schema/data/config_schema_v3.9.json
version: "3.9"

services:
  server:
    build: ./
    container_name: server
    ports:
      - "5000:5000"
